(() => {
 const byId=id=>document.getElementById(id);
 let latest,lastQueue='',artSources={},localError='';
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const format=ms=>{const s=Math.max(0,Math.floor((ms||0)/1000));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');};
 function setArt(id,fallback,src){if(artSources[id]===src)return;artSources[id]=src;const image=byId(id),empty=byId(fallback);const valid=/^data:image\/(png|jpeg|webp);base64,/.test(src)||/^https:\/\/i\.scdn\.co\//.test(src);image.classList.toggle('hidden',!valid);empty.classList.toggle('hidden',valid);image.onerror=()=>{image.classList.add('hidden');empty.classList.remove('hidden');};if(valid)image.src=src;else image.removeAttribute('src');}
 window.renderMusic=data=>{latest=data;const native=data.spotifyDesktop||{},api=data.spotifyQueue||{};const music=native.connected?native:api.current?{...api.current,playing:api.playing,positionMs:api.positionMs,updatedAt:api.updatedAt,connected:true}:native;setArt('compactCover','compactCoverFallback',music.artwork||'');setArt('heroCover','heroCoverFallback',music.artwork||'');byId('heroTitle').textContent=music.title||'A little music. A little focus.';byId('heroArtist').textContent=music.artist||'Open Spotify to choose your soundtrack.';byId('heroAlbum').textContent=music.album||'';byId('playingBadge').textContent=music.connected?(music.playing?'Playing':'Paused'):'No track yet';byId('compactEqualizer').classList.toggle('playing',!!music.playing);byId('heroToggle').textContent=music.playing?'❚❚':'▶';byId('heroToggle').setAttribute('aria-label',music.playing?'Pause Spotify':'Play Spotify');byId('heroStatus').textContent=native.connected?'Connected to Spotify desktop.':native.message||'Open Spotify and play a song to connect.';for(const id of ['heroPrevious','heroToggle','heroNext'])byId(id).disabled=!native.connected;
  const elapsed=Math.min(music.durationMs||0,Math.max(0,(music.positionMs||0)+(music.playing?Math.max(0,Date.now()-(music.updatedAt||Date.now())):0)));for(const prefix of ['hero','compact']){byId(prefix+'Elapsed').textContent=format(elapsed);byId(prefix+'Duration').textContent=format(music.durationMs);byId(prefix+'Progress').style.width=(music.durationMs?100*elapsed/music.durationMs:0)+'%';}
  byId('musicConnectionBadge').textContent=api.connected?'Spotify queue connected':'Spotify desktop';byId('queueCount').textContent=api.queue?.length||0;byId('queueDevice').textContent=api.device?'Playing on '+api.device:'Your Spotify playback queue';byId('queueRefresh').disabled=!api.connected;byId('queueNotConnected').classList.toggle('hidden',!!api.connected);byId('queueAddForm').classList.toggle('hidden',!api.connected);byId('queueNotice').classList.toggle('hidden',!api.connected);byId('queueDisconnect').classList.toggle('hidden',!api.connected);byId('queueSetupBody').classList.toggle('hidden',!!api.connected);byId('queueSetupTitle').textContent=api.connected?'Spotify is connected':'Connect Spotify queue';byId('queueSetupHint').textContent=api.connected?'Queue access is saved securely on this Windows account.':'One-time setup for Spotify Premium. This connects Still directly to Spotify.';byId('queueCancel').classList.toggle('hidden',!api.pending);byId('queueConnect').disabled=!!api.pending;byId('queueConnect').textContent=api.pending?'Waiting for browser approval…':'Connect Spotify';byId('queueError').classList.toggle('hidden',!(api.error||localError));byId('queueError').textContent=api.error||localError;
  const key=JSON.stringify([api.connected,api.queue,api.loaded]);if(lastQueue!==key){lastQueue=key;byId('queueList').innerHTML=api.connected?(api.queue?.length?api.queue.map((t,i)=>`<div class="queue-row"><span class="queue-number">${i+1}</span>${/^https:\/\/i\.scdn\.co\//.test(t.artwork)?`<img class="queue-art" src="${escape(t.artwork)}" alt="">`:'<span class="queue-art">♫</span>'}<div class="queue-info"><b title="${escape(t.title)}">${escape(t.title)}</b><span>${escape(t.artist)}</span></div><span class="queue-duration">${format(t.durationMs)}</span><button class="text-button" data-play-uri="${escape(t.uri)}" ${/^spotify:(track|episode):[A-Za-z0-9]{22}$/.test(t.uri)?'':'disabled'} aria-label="Play ${escape(t.title)} now">Play now</button></div>`).join(''):`<div class="empty-tasks">${api.loaded?'Your queue is empty. Add a song below.':'Loading your Spotify queue…'}</div>`):'';}
 };
 async function action(name,payload,button,success){const label=button?.textContent;if(button){button.disabled=true;button.textContent='Working…';}try{const result=await window.still.act(name,payload);if(!result.ok){localError=result.error;byId('queueError').textContent=result.error;byId('queueError').classList.remove('hidden');toast(result.error);return false;}localError='';if(success)toast(success);return true;}catch{toast('Could not reach Spotify. Please try again.');return false;}finally{if(button){button.disabled=false;button.textContent=label;}latest=await window.still.get();window.renderMusic(latest);}}
 byId('openMusicPage').onclick=()=>page('music');byId('heroOpenSpotify').onclick=()=>act('openSpotifyApp');byId('heroToggle').onclick=()=>musicControl('toggle',byId('heroToggle'));byId('heroPrevious').onclick=()=>musicControl('previous',byId('heroPrevious'));byId('heroNext').onclick=()=>musicControl('next',byId('heroNext'));byId('spotifyDeveloper').onclick=()=>act('spotifyDeveloper');byId('copyRedirect').onclick=async()=>{await navigator.clipboard.writeText('http://127.0.0.1:17844/callback');toast('Redirect URI copied.');};
 byId('queueConnectForm').onsubmit=e=>{e.preventDefault();action('spotifyQueueConnect',byId('spotifyClientId').value.trim(),byId('queueConnect'));};byId('queueCancel').onclick=()=>action('spotifyQueueCancel',null,byId('queueCancel'));byId('queueDisconnect').onclick=()=>action('spotifyQueueDisconnect',null,byId('queueDisconnect'),'Spotify queue disconnected.');byId('queueRefresh').onclick=()=>action('spotifyQueueRefresh',null,byId('queueRefresh'));byId('queueAddForm').onsubmit=async e=>{e.preventDefault();if(await action('spotifyQueueAdd',byId('queueTrackInput').value.trim(),byId('queueAdd'),'Added to your Spotify queue.'))byId('queueTrackInput').value='';};byId('queueList').onclick=e=>{const button=e.target.closest('[data-play-uri]');if(button)action('spotifyQueuePlay',button.dataset.playUri,button,'Playback requested.');};
 window.still.get().then(window.renderMusic);
})();
