'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={music:'M9 18V5l11-2v13 M9 8l11-2 M5 16a4 3 0 1 0 0 6a4 3 0 0 0 0-6 M16 14a4 3 0 1 0 0 6a4 3 0 0 0 0-6',timer:'M12 8v5l3 2 M9 2h6 M12 2v3 M19 5l2 2 M12 5a8 8 0 1 0 0 16a8 8 0 0 0 0-16',layers:'m12 3 9 5-9 5-9-5 9-5 M3 12l9 5 9-5 M3 16l9 5 9-5',chart:'M4 3v17h17 M8 15v-4 M13 15V7 M18 15V4',settings:'M12 8a4 4 0 1 0 0 8a4 4 0 0 0 0-8 M9 3l-1 3-3 1-2 4 2 2v4l4 2 3-1 3 1 4-2v-4l2-2-2-4-3-1-1-3z',moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11',pin:'m9 3 8 0-1 6 3 4v2H6v-2l3-4V3 M12 15v7',mini:'M3 5h18v15H3z M12 12h6v5h-6z',sliders:'M4 7h16 M4 17h16 M8 4v6 M16 14v6',play:'m9 5 11 7-11 7V5',pause:'M8 5v14 M16 5v14',skip:'m5 5 10 7-10 7V5 M19 5v14',leaf:'M20 3C9 2 3 7 5 15c8 5 15-2 15-12 M4 21l12-13',clock:'M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0-18 M12 7v5l4 2',check:'M5 12l4 4L19 6',flame:'M13 2c2 7-3 6-1 11 2-1 3-3 3-5 8 9 3 14-3 14S2 17 6 10c0 4 3 4 3 1 0-4 3-5 4-9',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3 M8 12l3 3 5-6',link:'m10 14 4-4 M8 16l-2 2a4 4 0 0 1-5-5l5-5a4 4 0 0 1 5 0 M16 8l2-2a4 4 0 0 1 5 5l-5 5a4 4 0 0 1-5 0',download:'M12 3v12 m-5-5 5 5 5-5 M4 16v5h16v-5'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.leaf}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let state,selected,view='focus',editingId=null,toastTimer,lastTasks='',lastPlans='',lastMusic=null,lastStats='',confirmAction;
const compact=new URLSearchParams(location.search).has('mini');if(compact){document.body.classList.add('mini-body');$('miniView').classList.remove('hidden');}
const time=seconds=>{seconds=Math.max(0,Math.ceil(seconds));return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`;};
const duration=seconds=>seconds>=3600?`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`:`${Math.floor(seconds/60)}m`;
const dayKey=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4500);}
async function act(name,payload){const r=await window.still.act(name,payload);if(!r.ok)toast(r.error);return r.ok;}
function page(name){view=name;document.querySelectorAll('.page').forEach(el=>el.classList.toggle('hidden',el.id!=='page-'+name));document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.page===name));$('crumb').textContent={focus:'Focus session',plans:'My plans',music:'Music & queue',stats:'Insights',settings:'Settings & connections'}[name];if(state)render(state);}
document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>page(el.dataset.page));
function streak(){let count=0,d=new Date();if(!(state.daily[dayKey(d)]>0))d.setDate(d.getDate()-1);while(state.daily[dayKey(d)]>0){count++;d.setDate(d.getDate()-1);}return count;}
let alarmContext,alarmNodes=[];
async function chime(kind='break',preview=false){
 if(compact||(!preview&&!state.settings.sound))return;
 const volume=Math.max(0,Math.min(100,state.settings.alarmVolume??70))/100;
 if(!volume){if(preview)toast('Raise the alarm volume to hear a preview.');return;}
 try{
  alarmContext ||= new AudioContext();
  if(alarmContext.state==='suspended')await alarmContext.resume();
  for(const node of alarmNodes){try{node.stop();}catch{}}alarmNodes=[];
  const notes=kind==='break'?[784,659,523]:kind==='focus'?[523,659,784]:[523,659,784,1047];
  const now=alarmContext.currentTime;
  for(let repeat=0;repeat<3;repeat++)notes.forEach((frequency,i)=>{
   const t=now+repeat*1.65+i*.3,o=alarmContext.createOscillator(),g=alarmContext.createGain();
   o.type='sine';o.frequency.value=frequency;o.connect(g);g.connect(alarmContext.destination);
   g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume*.28,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+.48);
   o.start(t);o.stop(t+.5);o.onended=()=>{o.disconnect();g.disconnect();};alarmNodes.push(o);
  });
 }catch{toast('Could not play the alarm. Check your Windows audio output and try Preview.');}
}
function render(data){state=data;document.body.dataset.theme=data.settings.theme;selected=state.plans.some(p=>p.id===selected)?selected:state.plans[0]?.id;const s=state.session,p=s||state.plans.find(p=>p.id===selected);if(!p)return;const intervals=p.intervals,index=s?.index||0,phase=intervals[index],running=s?.status==='running',left=s?s.remaining:phase.minutes*60;
 if(data.event&&!compact){if(data.event==='Interval complete'){chime(s?phase.type:'complete');toast(s?`${phase.type==='break'?'Time for a break.':'Ready for your next focus interval.'}`:'Session finished. Take a moment to enjoy your progress.');}else toast(data.event);}
 if(compact){$('miniPhase').textContent=s?(running?phase.type.toUpperCase():'PAUSED'):'READY WHEN YOU ARE';$('miniTime').textContent=time(left);$('miniName').textContent=p.name;$('miniToggle').textContent=s?(running?'Pause':'Resume'):'Start focus';return;}
 $('dateLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();
 const planJSON=JSON.stringify(state.plans);if(lastPlans!==planJSON){lastPlans=planJSON;$('planSelect').innerHTML=state.plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');renderPlans();}
 $('planSelect').value=s?.planId||selected;$('planSelect').disabled=!!s;$('planSummary').textContent=`${duration(intervals.filter(i=>i.type==='focus').reduce((t,i)=>t+i.minutes*60,0))} focus · ${intervals.filter(i=>i.type==='break').length} breaks`;
 $('phaseLabel').textContent=s?(running?(phase.type==='break'?'BREATHE & RECHARGE':'IN YOUR FOCUS ZONE'):'PAUSED • TAKE YOUR TIME'):'READY WHEN YOU ARE';$('timer').textContent=time(left);$('timerRing').style.setProperty('--progress',`${s?(1-left/(phase.minutes*60))*100:0}%`);
 const focusIndex=intervals.slice(0,index+1).filter(i=>i.type==='focus').length,focusCount=intervals.filter(i=>i.type==='focus').length;$('roundLabel').textContent=phase.type==='break'?'A little rest goes a long way':`Focus interval ${focusIndex} of ${focusCount}`;
 $('intervalDots').innerHTML=intervals.map((i,k)=>`<span title="${i.type} · ${Math.round(i.minutes)} min" class="interval-dot ${i.type} ${k<index?'done':k===index?'current':''}"></span>`).join('');
 $('startBtn').innerHTML=icon(running?'pause':'play')+`<span>${s?(running?'Pause session':'Resume focus'):'Start focus'}</span>`;$('skipBtn').classList.toggle('hidden',!s);$('breakBtn').disabled=!s||phase.type==='break';$('endBtn').disabled=!s;
 $('timerHint').textContent=s?(phase.type==='break'?'Step away, stretch, and let your mind reset.':`${duration(s.focusSeconds)} of focused time. Keep showing up for yourself.`):'A clear intention is a good place to start.';
 const today=dayKey(new Date());$('todayFocus').textContent=duration(state.daily[today]||0);$('todaySessions').textContent=state.history.filter(x=>x.status==='completed'&&dayKey(new Date(x.endedAt))===today).length;$('streak').textContent=`${streak()} ${streak()===1?'day':'days'}`;
 const tasks=s?.tasks||p.tasks.map((text,i)=>({id:String(i),text,done:false})),tasksKey=JSON.stringify([!!s,tasks]);if(tasksKey!==lastTasks){lastTasks=tasksKey;$('taskList').innerHTML=tasks.length?tasks.map(t=>`<div class="task ${t.done?'done':''}"><input type="checkbox" id="task-${esc(t.id)}" data-task="${esc(t.id)}" ${t.done?'checked':''} ${s?'':'disabled'}><label for="task-${esc(t.id)}">${esc(t.text)}</label>${s?`<button class="icon-button" data-delete-task="${esc(t.id)}" aria-label="Remove task">×</button>`:''}</div>`).join(''):`<div class="empty-tasks">${s?'What’s one thing you want to accomplish?':'A fresh start, a little intention.<br>Add tasks to your plan or start a session.'}</div>`;}
 const done=tasks.filter(t=>t.done).length;$('taskCount').textContent=`${done} / ${tasks.length}`;$('taskProgress').style.width=`${tasks.length?done/tasks.length*100:0}%`;$('taskInput').disabled=!s;$('taskForm').querySelector('button').disabled=!s;$('taskHint').textContent=s?'Your checklist is saved with this session.':'Plan intentions will appear when you start.';
 $('siteChips').innerHTML=p.sites.length?p.sites.map(d=>`<span class="site-chip">${esc(d)}</span>`).join(''):'<span class="micro">No websites selected for this plan.</span>';
 const blocked=s&&running&&phase.type==='focus'&&p.sites.length; $('shieldStatus').textContent=state.extensionConnected?(blocked?'Shield syncing / on':'Connected · idle'):'Not connected';$('shieldHint').textContent=state.extensionConnected?'Your browser syncs every 30 seconds. Breaks and pauses release the shield.':'Connect the browser extension to block sites during focus.';
 if(lastMusic!==state.spotify){lastMusic=state.spotify;$('musicEmpty').classList.toggle('hidden',!!lastMusic);$('musicPlayer').classList.toggle('hidden',!lastMusic);$('musicPlayer').replaceChildren();if(lastMusic){const frame=document.createElement('iframe');frame.src=lastMusic.replace('open.spotify.com/','open.spotify.com/embed/')+'?utm_source=generator&theme=0';frame.title='Spotify player';$('embedStatus').textContent='Loading Spotify… If the player stays blank, use the desktop controls or open the web player.';$('embedStatus').classList.remove('hidden');frame.onload=()=>{$('embedStatus').textContent='Link saved. Spotify may limit this embedded player to previews.';};frame.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';$('musicPlayer').appendChild(frame);}}
 const music=state.spotifyDesktop||{};$('desktopTrack').textContent=music.connected?(music.title||'Spotify is ready'):'Your Spotify music, alongside your focus.';$('desktopArtist').textContent=music.connected?(music.artist||''):'';$('desktopControls').classList.toggle('hidden',!music.connected);$('spotifyToggle').textContent=music.playing?'Pause':'Play';$('connectSpotify').textContent=music.connected?'Refresh player':'Connect desktop player';$('desktopStatus').textContent=music.message||(music.connected?'Connected to Spotify on this computer.':'Open Spotify and play a song once, then connect.');
 window.renderMusic?.(state);
 $('pinBtn').querySelector('span').textContent=state.pinned?'Unpin window':'Pin window';$('autoAdvance').checked=state.settings.autoAdvance;$('soundSetting').checked=state.settings.sound;if(document.activeElement!==$('alarmVolume'))$('alarmVolume').value=state.settings.alarmVolume??70;$('alarmVolumeLabel').textContent=(state.settings.alarmVolume??70)+'%';$('darkSetting').checked=state.settings.theme==='dark';$('pairKey').value=state.token;
 const warning=[state.loadWarning,state.bridgeError].filter(Boolean).join(' ');$('warning').classList.toggle('hidden',!warning);$('warning').textContent=warning;
 if(view==='stats'){const key=JSON.stringify([state.history,state.daily,Math.floor(s?.focusSeconds||0)]);if(key!==lastStats){lastStats=key;renderStats();}}
}
function renderPlans(){$('plansGrid').innerHTML=state.plans.map(p=>{const f=p.intervals.filter(i=>i.type==='focus').reduce((t,i)=>t+i.minutes,0),b=p.intervals.filter(i=>i.type==='break').reduce((t,i)=>t+i.minutes,0);return `<article class="card plan-card"><span class="plan-icon">${icon('layers')}</span><h2>${esc(p.name)}</h2><p>${f} minutes to make room for what matters.</p><div class="plan-timeline">${p.intervals.map(i=>`<span class="${i.type}" style="flex:${i.minutes}" title="${i.type}: ${i.minutes} min"></span>`).join('')}</div><div class="plan-meta">${p.intervals.length} intervals · ${b}m breaks<br>${p.sites.length} blocked websites · ${p.tasks.length} intentions</div><div class="plan-actions"><button class="primary small" data-use="${esc(p.id)}">Use plan ${icon('play')}</button><button class="secondary small" data-edit="${esc(p.id)}">Edit</button><button class="text-button delete-plan" data-delete="${esc(p.id)}">Delete</button></div></article>`;}).join('');}
function renderStats(){const total=Object.values(state.daily).reduce((a,b)=>a+b,0),completed=state.history.filter(s=>s.status==='completed').length,done=state.history.reduce((n,s)=>n+s.tasks.filter(t=>t.done).length,0)+(state.session?.tasks.filter(t=>t.done).length||0);$('statCards').innerHTML=[[duration(total),'Total focus time','Every minute of actual focus'],[completed,'Completed sessions','Full plans with no skips'],[done,'Intentions completed','Small wins, adding up'],[`${streak()} days`,'Current streak','Any focused time counts']].map(([v,l,h])=>`<article class="card stat-card"><span>${l}</span><b>${v}</b><small>${h}</small></article>`).join('');
 const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return {label:d.toLocaleDateString(undefined,{weekday:'short'}),value:state.daily[dayKey(d)]||0};});const max=Math.max(60,...days.map(d=>d.value));$('weekTotal').textContent=duration(days.reduce((s,d)=>s+d.value,0))+' this week';$('chart').innerHTML=days.map(d=>`<div class="chart-col"><span class="bar-value">${duration(d.value)}</span><div class="bar-track"><div class="bar" style="height:${d.value/max*100}%"></div></div><span>${d.label}</span></div>`).join('');
 $('history').innerHTML=state.history.length?state.history.slice(0,100).map(s=>`<div class="history-row"><div><b>${esc(s.name)}</b><small>${new Date(s.endedAt).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div><span>${duration(s.focusSeconds)} focused</span><span>${s.tasks.filter(t=>t.done).length} / ${s.tasks.length} tasks</span><span class="pill ${s.status==='completed'?'':'neutral'}">${s.status==='completed'?'Completed':'Ended early'}</span></div>`).join(''):'<div class="empty-tasks">Your story starts with one session.<br>Completed and ended sessions will appear here.</div>';}
function ask(title,message,action){$('confirmTitle').textContent=title;$('confirmText').textContent=message;confirmAction=action;$('confirmDialog').showModal();}
$('confirmCancel').onclick=()=>$('confirmDialog').close();$('confirmYes').onclick=()=>{$('confirmDialog').close();confirmAction?.();};
const toggle=()=>act(state.session?(state.session.status==='running'?'pause':'resume'):'start',selected||state.plans[0].id);
$('startBtn').onclick=toggle;$('miniToggle').onclick=toggle;$('expandBtn').onclick=()=>act('expand');$('pinBtn').onclick=()=>act('pin');$('miniBtn').onclick=()=>act('mini');
$('planSelect').onchange=e=>{selected=e.target.value;render(state);};$('skipBtn').onclick=()=>ask('Move to the next interval?','Your actual focus time is saved. A plan with skipped intervals is recorded as ended early.',()=>act('skip'));$('endBtn').onclick=()=>ask('Finish for now?','Your focus time and completed intentions will be saved. You can start a fresh session whenever you’re ready.',()=>act('end'));
$('breakBtn').onclick=()=>$('breakDialog').showModal();$('cancelBreak').onclick=()=>$('breakDialog').close();$('breakForm').onsubmit=async e=>{e.preventDefault();if(await act('break',Number($('breakMinutes').value)))$('breakDialog').close();};
$('taskForm').onsubmit=async e=>{e.preventDefault();if(await act('taskAdd',$('taskInput').value))$('taskInput').value='';};$('taskList').onchange=e=>{if(e.target.dataset.task)act('taskToggle',e.target.dataset.task);};$('taskList').onclick=e=>{const b=e.target.closest('[data-delete-task]');if(b)act('taskDelete',b.dataset.deleteTask);};
$('shieldSetup').onclick=()=>page('settings');$('themeBtn').onclick=()=>act('settings',{theme:state.settings.theme==='dark'?'light':'dark'});$('autoAdvance').onchange=e=>act('settings',{autoAdvance:e.target.checked});$('soundSetting').onchange=e=>act('settings',{sound:e.target.checked});$('darkSetting').onchange=e=>act('settings',{theme:e.target.checked?'dark':'light'});
$('alarmVolume').oninput=e=>$('alarmVolumeLabel').textContent=e.target.value+'%';$('alarmVolume').onchange=e=>act('settings',{alarmVolume:Number(e.target.value)});$('previewBreak').onclick=()=>chime('break',true);$('previewFocus').onclick=()=>chime('focus',true);
$('spotifyForm').onsubmit=async e=>{e.preventDefault();const input=$('spotifyInput').value.trim();$('spotifyError').classList.add('hidden');if(!input){$('spotifyError').textContent='Paste a Spotify link first. To connect your desktop app, use Connect desktop player above.';$('spotifyError').classList.remove('hidden');$('spotifyInput').focus();return;}const button=$('saveSpotifyLink');button.disabled=true;button.textContent='Saving…';try{const r=await window.still.act('spotify',input);if(!r.ok){$('spotifyError').textContent=r.error;$('spotifyError').classList.remove('hidden');}else{$('playlistDetails').open=true;toast('Spotify link saved.');}}catch{$('spotifyError').textContent='Could not save the link. Please restart Still and try again.';$('spotifyError').classList.remove('hidden');}finally{button.disabled=false;button.textContent='Save playlist link';}};
$('musicEdit').onclick=()=>{$('playlistDetails').open=true;$('musicEmpty').classList.remove('hidden');$('spotifyInput').value=state.spotify;$('spotifyInput').focus();};$('openSpotify').onclick=()=>act('openSpotify');$('openSpotifyApp').onclick=async()=>{if(await act('openSpotifyApp'))toast('Opening Spotify. Play a song there, then connect the desktop player.');};$('clearSpotify').onclick=async()=>{if(await act('unlinkSpotify'))toast('Spotify link removed.');};
async function musicControl(command,button){const label=button.textContent;button.disabled=true;button.textContent='Connecting…';try{const r=await window.still.act('spotifyDesktop',command);if(!r.ok){$('desktopStatus').textContent=r.error;toast(r.error);}else if(command==='status')toast('Spotify desktop player connected.');}catch{$('desktopStatus').textContent='Could not reach Spotify. Restart Still and try again.';}finally{button.disabled=false;button.textContent=label;render(await window.still.get());}}
$('connectSpotify').onclick=()=>musicControl('status',$('connectSpotify'));$('spotifyToggle').onclick=()=>musicControl('toggle',$('spotifyToggle'));$('spotifyPrevious').onclick=()=>musicControl('previous',$('spotifyPrevious'));$('spotifyNext').onclick=()=>musicControl('next',$('spotifyNext'));
$('copyKey').onclick=async()=>{await navigator.clipboard.writeText(state.token);toast('Pairing key copied.');};$('extensionFolder').onclick=()=>act('extensionFolder');$('exportBtn').onclick=$('exportStats').onclick=()=>act('export');$('importBtn').onclick=()=>act('import');
function addInterval(type='focus',minutes=type==='focus'?25:5){const row=document.createElement('div');row.className='interval-row';row.innerHTML=`<select aria-label="Interval type"><option value="focus" ${type==='focus'?'selected':''}>Focus</option><option value="break" ${type==='break'?'selected':''}>Break</option></select><input aria-label="Minutes" type="number" min="1" max="240" required value="${minutes}"><span>min</span><button class="icon-button" type="button" aria-label="Remove interval">×</button>`;row.querySelector('button').onclick=()=>{row.remove();planTotal();};row.oninput=planTotal;$('intervalEditor').appendChild(row);planTotal();}
function planTotal(){const rows=[...$('intervalEditor').children];$('planTotal').textContent=`${rows.length} intervals · ${rows.reduce((s,r)=>s+Number(r.querySelector('input').value),0)} minutes total`;}
function editPlan(id){const p=state.plans.find(p=>p.id===id);editingId=p?.id||null;$('dialogTitle').textContent=p?'Edit your plan':'Create a plan';$('planName').value=p?.name||'';$('planSites').value=p?.sites.join(', ')||'';$('planTasks').value=p?.tasks.join('\n')||'';$('intervalEditor').replaceChildren();(p?.intervals||[{type:'focus',minutes:25},{type:'break',minutes:5},{type:'focus',minutes:25}]).forEach(i=>addInterval(i.type,i.minutes));$('planDialog').showModal();}
$('newPlan').onclick=()=>editPlan();$('editCurrent').onclick=()=>{if(state.session)toast('Edits apply to future sessions. Your active session keeps its current plan.');editPlan(state.session?.planId||selected);};$('closeDialog').onclick=()=>$('planDialog').close();$('addFocus').onclick=()=>addInterval();$('addBreak').onclick=()=>addInterval('break');
$('planForm').onsubmit=async e=>{e.preventDefault();const p={name:$('planName').value,intervals:[...$('intervalEditor').children].map(r=>({type:r.querySelector('select').value,minutes:Number(r.querySelector('input').value)})),sites:$('planSites').value.split(/[,\n]/).map(s=>s.trim()).filter(Boolean),tasks:$('planTasks').value.split('\n').filter(Boolean)};if(editingId)p.id=editingId;if(await act('savePlan',p)){$('planDialog').close();toast('Your plan is saved.');}};
$('plansGrid').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)editPlan(b.dataset.edit);if(b.dataset.use){if(state.session){toast('End the active session before switching plans.');return;}selected=b.dataset.use;page('focus');}if(b.dataset.delete)ask('Delete this plan?','Your recorded session history will stay saved.',()=>act('deletePlan',b.dataset.delete));};
window.still.onState(render);window.still.get().then(render);
