'use strict';
const crypto=require('node:crypto'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {spotifyLink}=require('./spotify');
const REDIRECT='http://127.0.0.1:17844/callback';
function track(item){if(!item)return null;return {uri:typeof item.uri==='string'?item.uri:'',title:String(item.name||'Untitled track'),artist:(item.artists||[]).map(a=>a.name).join(', ')||item.show?.publisher||'',album:item.album?.name||item.show?.name||'',artwork:(item.album?.images||item.images||[]).find(i=>/^https:\/\/i\.scdn\.co\//.test(i.url))?.url||'',durationMs:Number(item.duration_ms)||0,url:item.external_urls?.spotify||''};}
function trackUri(input){const url=spotifyLink(input);const parts=new URL(url).pathname.split('/');if(!['track','episode'].includes(parts[1]))throw Error('Add a song or episode link. A playlist link cannot be added as a single queue item.');return `spotify:${parts[1]}:${parts[2]}`;}
class SpotifyAPI {
 constructor({root,storage,openExternal,fetchImpl=fetch,onChange=()=>{}}){this.file=path.join(root,'spotify-auth.enc');this.storage=storage;this.openExternal=openExternal;this.fetch=fetchImpl;this.onChange=onChange;this.auth=null;this.generation=0;this.listener=null;this.pending=null;this.refreshing=null;this.syncing=null;this.cooldown=0;this.view={connected:false,pending:false,clientId:'',queue:[],current:null,playing:false,positionMs:0,updatedAt:0,error:'',loaded:false};try{if(fs.existsSync(this.file)&&storage.isEncryptionAvailable()){this.auth=JSON.parse(storage.decryptString(fs.readFileSync(this.file)));this.view.connected=!!this.auth.refresh_token;this.view.clientId=this.auth.clientId||'';}}catch{this.view.error='Please reconnect Spotify on this Windows account.';}}
 snapshot(){return {...this.view};}
 notify(){this.onChange();}
 persist(){if(!this.storage.isEncryptionAvailable())throw Error('Windows credential encryption is unavailable. Spotify sign-in cannot be saved.');fs.mkdirSync(path.dirname(this.file),{recursive:true});const bytes=this.storage.encryptString(JSON.stringify(this.auth));fs.writeFileSync(this.file+'.tmp',bytes);fs.renameSync(this.file+'.tmp',this.file);}
 stopLogin(){clearTimeout(this.loginTimeout);this.listener?.close();this.listener=null;this.pending=null;this.view.pending=false;}
 async connect(clientId){clientId=String(clientId||'').trim();if(!/^[a-fA-F0-9]{32}$/.test(clientId))throw Error('Paste the 32-character Client ID from your Spotify developer app. Do not use the client secret.');if(!this.storage.isEncryptionAvailable())throw Error('Windows credential encryption is unavailable.');this.stopLogin();const generation=++this.generation;const verifier=crypto.randomBytes(48).toString('base64url'),state=crypto.randomBytes(32).toString('hex');this.pending={verifier,state,clientId};
  const listener=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','text/plain; charset=utf-8');res.setHeader('Content-Security-Policy',"default-src 'none'");const url=new URL(req.url,REDIRECT);if(req.method!=='GET'||url.pathname!=='/callback'){res.writeHead(404);return res.end('Not found');}const pending=this.pending;if(!pending||url.searchParams.get('state')!==pending.state){res.writeHead(400);return res.end('This sign-in request is not valid. Return to Still and connect again.');}this.pending=null;
   try{if(url.searchParams.has('error'))throw Error('Spotify authorization was cancelled.');const code=url.searchParams.get('code');if(!code)throw Error('Spotify returned no authorization code.');const token=await this.tokenRequest({grant_type:'authorization_code',code,redirect_uri:REDIRECT,client_id:pending.clientId,code_verifier:pending.verifier});if(generation!==this.generation)throw Error('Spotify connection was cancelled.');if(!token.access_token||!token.refresh_token)throw Error('Spotify did not complete authorization.');this.auth={...token,clientId:pending.clientId,expiresAt:Date.now()+token.expires_in*1000};this.persist();this.view.connected=true;this.view.clientId=pending.clientId;this.view.error='';res.end('Spotify is connected to Still. You can close this tab and return to your focus session.');this.stopLogin();this.notify();await this.sync();}catch(err){this.view.error=err.message;if(!res.writableEnded){res.writeHead(400);res.end('Spotify connection failed. Return to Still for details.');}this.stopLogin();this.notify();}});
  this.listener=listener;try{await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(17844,'127.0.0.1',resolve);});}catch{this.stopLogin();throw Error('The Spotify sign-in port is already in use. Close other sign-in attempts and try again.');}
  this.view.pending=true;this.view.error='';this.loginTimeout=setTimeout(()=>{this.stopLogin();this.view.error='Sign-in expired. Click Connect Spotify to try again.';this.notify();},300000);const query=new URLSearchParams({client_id:clientId,response_type:'code',redirect_uri:REDIRECT,scope:'user-read-playback-state user-modify-playback-state',state,code_challenge_method:'S256',code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url')});this.notify();try{await this.openExternal('https://accounts.spotify.com/authorize?'+query);}catch{this.stopLogin();throw Error('Could not open your browser for Spotify sign-in.');}
 }
 async tokenRequest(params){const r=await this.fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params).toString(),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Spotify sign-in expired or was refused. Reconnect and check your Client ID and redirect URI.');return r.json();}
 async accessToken(){if(!this.auth)throw Error('Connect your Spotify account to load the queue.');if(Date.now()<this.auth.expiresAt-60000)return this.auth.access_token;if(this.refreshing)return this.refreshing;const previous=this.auth;this.refreshing=(async()=>{const t=await this.tokenRequest({grant_type:'refresh_token',refresh_token:this.auth.refresh_token,client_id:this.auth.clientId});if(this.auth!==previous)throw Error('Spotify connection changed. Please try again.');this.auth={...this.auth,...t,refresh_token:t.refresh_token||this.auth.refresh_token,expiresAt:Date.now()+t.expires_in*1000};this.persist();return this.auth.access_token;})();try{return await this.refreshing;}finally{this.refreshing=null;}}
 async request(route,method='GET',body,retry=true){if(Date.now()<this.cooldown)throw Error('Spotify asked us to wait. Try again in '+Math.ceil((this.cooldown-Date.now())/1000)+' seconds.');const token=await this.accessToken();const r=await this.fetch('https://api.spotify.com/v1'+route,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});if(r.status===401&&retry){this.auth.expiresAt=0;return this.request(route,method,body,false);}if(r.status===429){this.cooldown=Date.now()+Math.max(10,Number(r.headers.get('retry-after'))||30)*1000;throw Error('Spotify is rate limiting requests. Please wait before refreshing.');}if(r.status===403)throw Error('Spotify denied access. Check Premium eligibility and add this Spotify account in your developer app’s User Management.');if(r.status===404)throw Error('No active Spotify player. Open Spotify, play a song, then refresh.');if(!r.ok)throw Error('Spotify could not complete that request ('+r.status+'). Try reconnecting.');return r.status===204?null:r.json();}
 async sync(){if(!this.auth)return;if(this.syncing)return this.syncing;const generation=this.generation;this.syncing=(async()=>{try{const [queue,playback]=await Promise.all([this.request('/me/player/queue'),this.request('/me/player')]);if(generation!==this.generation)return;this.view.queue=(queue?.queue||[]).map(track);this.view.current=track(playback?.item||queue?.currently_playing);this.view.playing=!!playback?.is_playing;this.view.positionMs=playback?.progress_ms||0;this.view.device=playback?.device?.name||'';this.view.updatedAt=Date.now();this.view.loaded=true;this.view.error='';}catch(err){if(generation!==this.generation)return;this.view.error=err.message;throw err;}finally{this.notify();}})();try{return await this.syncing;}finally{this.syncing=null;}}
 async add(input){await this.request('/me/player/queue?'+new URLSearchParams({uri:trackUri(input)}),'POST');await this.sync();}
 async play(uri){if(!/^spotify:(track|episode):[A-Za-z0-9]{22}$/.test(uri))throw Error('This queue item cannot be played directly.');await this.request('/me/player/play','PUT',{uris:[uri]});await this.sync();}
 disconnect(){this.generation++;this.stopLogin();this.auth=null;if(fs.existsSync(this.file))fs.unlinkSync(this.file);this.view={connected:false,pending:false,clientId:'',queue:[],current:null,playing:false,positionMs:0,updatedAt:0,error:'',loaded:false};this.notify();}
}
module.exports={SpotifyAPI,track,trackUri,REDIRECT};
