const test=require('node:test'),assert=require('node:assert/strict');
const {Engine,initial,validatePlan,domain}=require('../engine');
function setup(){let now=1700000000000;const e=new Engine(initial(),()=>now);const advance=n=>{for(let i=0;i<n;i++){now+=1000;e.tick();}};return {e,advance,sleep:n=>{now+=n*1000;e.tick();}};}
test('normalizes hostnames and rejects unsafe protocols',()=>{assert.equal(domain('https://www.Facebook.com/path'),'facebook.com');assert.equal(domain('javascript:alert(1)'),null);assert.equal(domain('file:///C:/'),null);});
test('validates plans and requires focus',()=>{assert.throws(()=>validatePlan({name:'x',intervals:[{type:'break',minutes:5}]}));assert.throws(()=>validatePlan({name:'x',intervals:[{type:'focus',minutes:0}]}));assert.equal(validatePlan({name:' x ',intervals:[{type:'focus',minutes:2}],sites:['facebook.com','www.facebook.com']}).sites.length,1);});
test('focus counts elapsed seconds; pause and breaks do not',()=>{const {e,advance}=setup();e.start(e.data.plans[0].id);advance(30);assert.equal(e.data.session.focusSeconds,30);e.pause();advance(50);assert.equal(e.data.session.focusSeconds,30);e.resume();e.breakNow(1);advance(60);assert.equal(e.current().type,'focus');assert.equal(e.data.session.remaining,1470);advance(10);assert.equal(e.data.session.focusSeconds,40);});
test('sleep pauses without adding unattended time',()=>{const {e,advance,sleep}=setup();e.start(e.data.plans[0].id);advance(10);sleep(120);assert.equal(e.data.session.status,'paused');assert.equal(e.data.session.focusSeconds,10);});
test('finishing a whole plan records exactly one completion',()=>{const {e,advance}=setup();const p=validatePlan({name:'Short',intervals:[{type:'focus',minutes:1},{type:'break',minutes:1},{type:'focus',minutes:1}]});e.data.plans.push(p);e.start(p.id);advance(180);assert.equal(e.data.session,null);assert.equal(e.data.history.length,1);assert.equal(e.data.history[0].status,'completed');assert.equal(e.data.history[0].focusSeconds,120);assert.equal(Object.values(e.data.daily).reduce((a,b)=>a+b,0),120);});
test('manual advancement pauses at boundaries and skips are not completions',()=>{const {e,advance}=setup();e.data.settings.autoAdvance=false;e.start(e.data.plans[0].id);advance(1500);assert.equal(e.data.session.status,'paused');assert.equal(e.current().type,'break');while(e.data.session)e.next();assert.equal(e.data.history[0].status,'ended');});
test('plans remain independent from session tasks and inserted breaks',()=>{const {e}=setup();e.data.plans[0].tasks=['Read'];e.start(e.data.plans[0].id);e.data.session.tasks[0].done=true;e.breakNow(2);assert.equal(e.data.plans[0].intervals.length,5);assert.deepEqual(e.data.plans[0].tasks,['Read']);});
