const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {SpotifyAPI,track,trackUri,REDIRECT}=require('../spotify-api');
const id='37i9dQZF1DX8NTLI2TtZa6';
function fixture(fetchImpl){const root=fs.mkdtempSync(path.join(os.tmpdir(),'still-spotify-test-'));let opened='';const storage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()};const api=new SpotifyAPI({root,storage,fetchImpl,openExternal:async u=>{opened=u;}});return {api,root,opened:()=>opened,close:()=>{api.stopLogin();fs.rmSync(root,{recursive:true,force:true});}};}
const json=(body,status=200,headers={})=>new Response(body===null?null:JSON.stringify(body),{status,headers});
test('normalizes queue tracks and only allows individual tracks or episodes',()=>{assert.equal(trackUri('spotify:track:'+id),'spotify:track:'+id);assert.throws(()=>trackUri('https://open.spotify.com/playlist/'+id),/playlist/);const result=track({uri:'spotify:track:'+id,name:'Song',artists:[{name:'Artist'}],duration_ms:150000,album:{images:[{url:'https://evil.example/image'}]}});assert.equal(result.artist,'Artist');assert.equal(result.artwork,'');});
test('connection validates Client ID and cannot save unencrypted credentials',async()=>{const f=fixture();try{await assert.rejects(f.api.connect('secret'),/Client ID/);f.api.storage.isEncryptionAvailable=()=>false;await assert.rejects(f.api.connect('a'.repeat(32)),/encryption/);}finally{f.close();}});
test('OAuth PKCE rejects a wrong state and exchanges a valid code; no tokens enter UI state',async()=>{let tokenBody;const f=fixture(async(url,opts)=>{if(url.includes('/api/token')){tokenBody=new URLSearchParams(opts.body);return json({access_token:'private-access',refresh_token:'private-refresh',expires_in:3600});}if(url.endsWith('/queue'))return json({queue:[],currently_playing:null});return json(null,204);});try{await f.api.connect('a'.repeat(32));const u=new URL(f.opened());assert.equal(u.origin,'https://accounts.spotify.com');assert.equal(u.searchParams.get('redirect_uri'),REDIRECT);assert.equal(u.searchParams.get('code_challenge_method'),'S256');const pending=f.api.pending;assert.equal(u.searchParams.get('code_challenge'),crypto.createHash('sha256').update(pending.verifier).digest('base64url'));const wrong=await fetch(REDIRECT+'?state=wrong&code=bad');assert.equal(wrong.status,400);assert(f.api.pending);const good=await fetch(REDIRECT+'?state='+pending.state+'&code=approved');assert.equal(good.status,200);await f.api.sync();assert.equal(tokenBody.get('code_verifier'),pending.verifier);assert.equal(f.api.snapshot().connected,true);assert(!JSON.stringify(f.api.snapshot()).includes('private-access'));assert(!JSON.stringify(f.api.snapshot()).includes('private-refresh'));assert(fs.existsSync(path.join(f.root,'spotify-auth.enc')));f.api.disconnect();assert(!fs.existsSync(path.join(f.root,'spotify-auth.enc')));}finally{f.close();}});
test('queue refresh, add, and play send expected API requests',async()=>{const calls=[];const f=fixture(async(url,opts)=>{calls.push({url,...opts});if(url.endsWith('/queue')&&opts.method==='GET')return json({queue:[{uri:'spotify:track:'+id,name:'Song'}]});if(url.endsWith('/me/player'))return json({is_playing:true,progress_ms:2000,device:{name:'Desktop'},item:{name:'Now',duration_ms:5000}});return json(null,204);});try{f.api.auth={access_token:'test',refresh_token:'test',expiresAt:Date.now()+3600000};await f.api.sync();assert.equal(f.api.view.queue.length,1);assert.equal(f.api.view.device,'Desktop');await f.api.add('spotify:track:'+id);assert(calls.some(c=>c.method==='POST'&&new URL(c.url).searchParams.get('uri')==='spotify:track:'+id));await f.api.play('spotify:track:'+id);assert(calls.some(c=>c.method==='PUT'&&JSON.parse(c.body).uris[0]==='spotify:track:'+id));await assert.rejects(f.api.play('spotify:playlist:'+id));}finally{f.close();}});
test('expired tokens refresh and retain the existing refresh token',async()=>{const f=fixture(async(url)=>url.includes('/api/token')?json({access_token:'fresh',expires_in:3600}):json({}));try{f.api.auth={clientId:'a'.repeat(32),access_token:'old',refresh_token:'retain',expiresAt:0};await f.api.request('/me/player');assert.equal(f.api.auth.access_token,'fresh');assert.equal(f.api.auth.refresh_token,'retain');}finally{f.close();}});
test('rate limits stop further requests until the cooldown expires',async()=>{let calls=0;const f=fixture(async()=>{calls++;return json({},429,{'retry-after':'60'});});try{f.api.auth={access_token:'test',expiresAt:Date.now()+3600000};await assert.rejects(f.api.request('/me/player'),/rate limiting/);await assert.rejects(f.api.request('/me/player'),/wait/);assert.equal(calls,1);}finally{f.close();}});
test('missing active device and forbidden playback have actionable errors',async()=>{const f=fixture(async()=>json({},404));try{f.api.auth={access_token:'test',expiresAt:Date.now()+3600000};await assert.rejects(f.api.request('/me/player'),/active Spotify player/);f.api.fetch=async()=>json({},403);await assert.rejects(f.api.request('/me/player'),/Premium/);}finally{f.close();}});
